 <section class="cart_area padding_top">
    <div class="container">
      <div class="cart_inner">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Ref</th>
                <th scope="col">Produit</th>
                <th scope="col">Prix</th>
                <th scope="col">Quantité</th>
                <th scope="col">Total</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <div class="media">
                    <div class="d-flex">
                      <h3><?= $basketItem['id'] ?></h3>
                    </div>
                    <div class="media-body">
                      <p><?= $basketItem['name'] ?></p>
                    </div>
                  </div>
                </td>
                <td>
                  <h5><?= number_format($basketItem['salePrice'], 2) ?> €</h5>
                </td>
                <td>
                  <div class="product_count">
                    <h5><?= number_format($basketItem['salePrice'] * $basketItem['quantity'], 2) ?> €</h5>
                    <td>
                     <button class="button button-cancel small" title="Supprimer l'article" data-meal-id="<?= $basketItem['mealId'] ?>">
                            <i class="fa fa-trash"></i>
                        </button>
                    </td>
                  </div>
                </td>
              </tr> 
              <tr>
                <td></td>
                <td></td>
                <td>
                  <h5>Total</h5>
                </td>
                <td>
                  <h5>$2160.00</h5>
                </td>
              </tr>
              <tr class="shipping_area">
                <td></td>
                <td></td>
                <td>
                  <h5>Shipping</h5>
                </td>
                <td>
                  <div class="shipping_box">
                    <ul class="list">
                      
                      <li>
                        <a href="#">Free Shipping</a>
                      </li>
                      <li class="active">
                        <a href="#">Local Delivery: $2.00</a>
                      </li>
                    </ul>
                </td>
              </tr>
            </tbody>
          </table>
          <div class="checkout_btn_inner float-right">
            <a class="btn_1" href="#">Poursuivre mes achats</a>
            <button id="validate-order" class="btn_1 checkout_btn_1" >Passer ma commande</button>
          </div>
        </div>
      </div>
  </section>


  <script src="<?= $wwwUrl ?>/js/classes/BasketSession.class.js"></script>
  <script src="<?= $wwwUrl ?>/js/classes/OrderForm.class.js"></script>
