
        

  <section class="cart_area padding_top">
    <div class="container">
      <div class="cart_inner">
        <h3 id="count"  class="hidden"><i class="fas fa-cart-plus"> </i> Vous avez <?=count($basketItems); ?> article(s) dans votre panier</h3>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Produit</th>
                <th scope="col">Prix</th>
                <th scope="col">Quantité</th>
                <th scope="col">Total</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <?php   
              foreach($basketItems as $basketItem): ?>
              <tr>
                <td>
                    <div class="media-body">
                      <p><?= $basketItem['name'] ?></p>
                    </div>
                </td>

                <td>
                  <h5><?= number_format($basketItem['salePrice'], 2) ?> €</h5>
                </td>
                <td>
                  <h5><?= number_format($basketItem['quantity']) ?></h5>
                </td>

                <td>
                  <div class="product_count">
                    <h5><?= number_format($basketItem['salePrice'] * $basketItem['quantity'], 2) ?> €</h5>
                  </div>
                </td>
                <td>
                   <div class="media-body">
                      <button class="btn btn-danger" title="Supprimer l'article" data-product-id="<?= $basketItem['productId'] ?>">
                        <i class="fa fa-trash"></i>
                      </button>
                    </div>
                </td>
              </tr> 
              <?php endforeach; ?>
              <tr >
                <td></td>
                <td></td>
                <td></td>
                <td>
                  <h5>Total</h5>
                </td>
                <td>
                  <h5><?php
                  $sum=0;
                   foreach($basketItems as $basketItem): $sum=$sum+($basketItem['salePrice'] * $basketItem['quantity']);  endforeach;echo(number_format($sum,2)); ?>€</h5>
                </td>
              </tr>
            </tbody>
          </table>
          <div class="checkout_btn_inner float-right">
            <a class="btn_1" href="#">Poursuivre mes achats</a>
            <button class="btn_1 checkout_btn_1" id="validate-order" >Passer ma commande</button>
          </div>       
        </div>
      </div>
    </div>
  </section>

         

        
     


 