<!doctype html>
<html lang="fr">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>home-IK</title>
    <link rel="icon" href="img/favicon.png">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/bootstrap.min.css">
    <!-- animate CSS -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/animate.css">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/owl.carousel.min.css">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/all.css">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/flaticon.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/themify-icons.css">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/magnific-popup.css">
    
    <!-- style CSS -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/custom.css">

    
    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>


    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
    <script src="<?= $wwwUrl ?>/js/classes/FormValidator.class.js"></script>

</head>

<body>
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="<?= $requestUrl ?>"> MY-HOME</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"><i class="fas fa-bars"></i></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="<?= $requestUrl ?>">Accueil</a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link " href="<?= $requestUrl ?>/products">
                                        Boutique
                                    </a>
                                </li>
                                <?php if($userSession->isAuthenticated() == false): ?>
                                 <li class="nav-item">
                                    <a class="nav-link" href="<?= $requestUrl ?>/user/login">Espace Client</a>
                                </li>
                                  <?php endif; ?>
                                <li class="nav-item">
                                    <a class="nav-link" href="<?= $requestUrl ?>/contact">Contactez nous</a>  
                                </li>
                            </ul>
                        </div>
                        <div class="hearer_icon d-flex">
                             <?php if($userSession->isAuthenticated() == true): ?>
                                <p class="welcome">Bonjour <strong><?= $userSession->getFullName() ?></strong> !</p>
                            <a href="<?= $requestUrl ?>/user/logout"><i class="fas fa-sign-out-alt"></i></a>
                            <?php endif; ?>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        
    </header>
    <!-- Header part end-->
    <main>
        <!-- Affichage du template lié à la vue -->
        <?php include $this->viewData['template'] ?>
    </main>
      <footer class="footer_part">
        <div class="copyright_part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="copyright_text">
                            <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script> Tous droits réservés | 
                            Ce modèle est fait avec <i class="ti-heart" aria-hidden="true"></i> par <a href="" target="_blank">IntissarKlach 3WAcademy </a></P>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="footer_icon social_icon">
                            <ul class="list-unstyled">
                                <li><a href="#" class="single_social_icon"><i class="fab fa-facebook-f"></i></a></li>
                                <li><a href="#" class="single_social_icon"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="#" class="single_social_icon"><i class="fas fa-globe"></i></a></li>
                                <li><a href="#" class="single_social_icon"><i class="fab fa-behance"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--::footer_part end::-->

    <!-- popper js -->
    <script src="<?= $wwwUrl ?>/js/popper.min.js"></script>
    <!-- bootstrap js -->
    <script src="<?= $wwwUrl ?>/js/bootstrap.min.js"></script>
    <!-- easing js -->
    <script src="<?= $wwwUrl ?>/js/jquery.magnific-popup.js"></script>
    <!-- swiper js -->
    <script src="<?= $wwwUrl ?>/js/swiper.min.js"></script>
    <!-- swiper js -->
    <script src="<?= $wwwUrl ?>/js/masonry.pkgd.js"></script>
    <!-- particles js -->
    <script src="<?= $wwwUrl ?>/js/owl.carousel.min.js"></script>
    <script src="<?= $wwwUrl ?>/js/jquery.nice-select.min.js"></script>
    <!-- slick js -->
  
    <!-- custom js -->
    <script src="<?= $wwwUrl ?>/js/custom.js"></script>

 
</body>

</html>