 


  <!--================Single Product Area =================-->
  <div class="product_image_area section_padding ">
    <div class="container" id="container" >
        <form data-order-step="run" id="order-form" class="generic-form   row s_product_inner justify-content-between ">
        <div class="col-lg-7 col-xl-7">
          <div class="product_slider_img">
              <div data-thumb="<?= $wwwUrl ?><?= $product['img']; ?>">
                <img src="<?= $wwwUrl ?><?= $product['img']; ?>" />
              </div>  
          </div>
        </div>
        <div class="col-lg-5 col-xl-4">
          <div class="s_product_text">
            <strong>Réf:</strong><span id="id"><?= $product['Id'];?></span>
            <h3 id="title"><?= $product['Title']; ?> -<?= $product['Color']; ?> </h3>
            <h2 id="price"><?= $product['Price']; ?>€</h2>
            <p>Déscription:<?= $product['Description']; ?>
            </p>
            <div class="card_area d-flex justify-content-between align-items-center">
              <div class="product_count">
                <span class="inumber-decrement"> <i class="ti-minus"></i></span>
                <input id="quantity"  type="text" name="quantity" data-name="Quantité" data-type="positive-integer" data-required class="input-number quantity"  value="1" min="1" max="20">
                <span class="number-increment"> <i class="ti-plus"></i></span>
              </div>
              <button type="submit" class="btn_3">Ajouter au panier</button>
            </div>
          </div>
        </div>
        </form>
    </div>
  </div>
  <!--================End Single Product Area =================-->

  <script src="<?= $wwwUrl ?>/js/classes/BasketSession.class.js"></script>
  <script src="<?= $wwwUrl ?>/js/classes/OrderForm.class.js"></script>

