

  <!-- ================ contact section start ================= -->
  <section class="contact-section padding_top">
    <div class="container">
   


      <div class="row">
        <div class="col-lg-4">
          <h2 class="contact-title">Get in Touch</h2>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>Buttonwood, California.</h3>
              <p>Rosemead, CA 91770</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
            <div class="media-body">
              <h3>00 (440) 9865 562</h3>
              <p>Mon to Fri 9am to 6pm</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3>support@colorlib.com</h3>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>
           <div class="d-none d-sm-block col-lg-8 ">
       <iframe width="100%" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12770.511352168016!2d10.2006248!3d36.8513882!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd820fc66162a8c3c!2s3W+academy!5e0!3m2!1sfr!2stn!4v1548410410093"  height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
      </div>
    </div>
  </section>
  <!-- ================ contact section end ================= -->

  